config/routes.rb
Rails.application.routes.draw do

	root 'static_pages#home'
	get 'signup' => 'users#new'
	get 'search' => 'search#search'	
	get 'login' 		=>	'sessions#new'
	post 'login'		=>	'sessions#create'
	delete 'logout' =>	'sessions#destroy'

	resources :users 

	resources :books, only: [:create, :destroy, :new]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if logged_in?
	  	@feed_items = current_user.feed.paginate( page: params[:page])
	  end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<%= provide(:title, "Home")%>
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
        <% if current_user.profile_picture? %>
          <%= image_tag(current_user.profile_picture.url, size: "280x210")%>
        <% end %>
        <br>
      </section>
      <section class="book_form">
        <%= link_to "Add a new book", new_book_path %>
      </section>
    </aside>
    <div class="col-md-8">
      <h2>Latest Book Feed</h2>
      <%= render 'shared/feed' %>    
    </div>
  </div>
<% else %>  
  <div class="container">
    <h1>Welcome to Book Share!</h1>
  	<h4>A place where you can sell your old books.</h4>
  	<h4>Or buy second hand books from your senoirs.</h4>
  	
    <p>To get started sign-up or just look around!</p>
    <h2 class="text-center">
      <%= link_to "Sign Up Now", signup_path , class: "btn btn-lg btn-primary"%>
    </h2>
  </div>
<% end %>