config/routes.rb
Rails.application.routes.draw do

	root 'static_pages#home'
	get 'signup' => 'users#new'
	get 'search' => 'search#search'	
	get 'login' 		=>	'sessions#new'
	post 'login'		=>	'sessions#create'
	delete 'logout' =>	'sessions#destroy'

	resources :users 

	resources :books, only: [:create, :destroy, :new]
end

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-fixed-bottom">
	<div class="container">
		<nav>
			<ul class="nav navbar-nav navbar-left">
				<li><%= link_to "Links", "#" %></li>
				<li><%= link_to "About", "#" %></li>
				<li><%= link_to "Help", "#" %></li>
				<li><%= link_to "Contact", "#" %></li>
			</ul>
		</nav>
	</div>	
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="container">
		<%= link_to "Book Share Logo", root_path , id: "header_logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Search", search_path %></li>
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "About", "#" %></li>
				<li><%= link_to "Help", "#" %></li>
				 <% if logged_in? %>
					<li><%= link_to "Users", users_path %></li>
        			<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						Account <b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li><%= link_to "Profile", current_user %></li>
						<li><%= link_to "Settings", edit_user_path(current_user) %></li>
						<li class="divider"></li>
						<li>
							<%= link_to "Log out", logout_path, method: "delete" %>
						</li>
					</ul>
					</li>
				<% else %>
					<li><%= link_to "Log in", login_path %></li>
				<% end %>

				</ul>
		</nav>
	</div>	
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title( yield(:title) )%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
  <br><br>
    <%= render "layouts/header" %>
    <% flash.each  do |msg_type, msg | %>
      <div class="text-center alert alert-<%= msg_type%> "><%=msg%></div>
    <% end %>
    <%= yield %>
		<%= render "layouts/footer" %>
		<%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>